### ISSUE TITLE
Not working in CB v1.2.6-pl

### ISSUE THREAD

**Issue by knightknight** [DashMedia/ContentBlocksButton#1]
MODx v2.3.5, ContentBlocks Button v1.0.0-pl and ContentBlocks v1.2.6-pl

ContentBlocks error: Uh oh, could not load the input type ContentBlocksButton

**Comment by pepebe** [comment]
Still not working in 1.6.3.

The button can be used in ContentBlocks Manager to create a new block.

Afterwards in shows up in the manager among the list of available blocks.

Picking it, caused a popup to appear:

![screenshot 2017-03-17 13 42 59](https://cloud.githubusercontent.com/assets/667315/24043741/5e4314c0-0b18-11e7-85fc-cae355309c90.png)

Also a 404 error is returned:

ContentBlocks is looking for
assets/components/contentblocksbutton/js/inputs/contentblocksbutton.js

But the only thing I have is:
assets/components/contentblocksbutton/js/inputs/ContentBlocksButton.js

That is easily fixed, but it is still not a solution.

If I pick the button now, the block-picker stays on top and the button is not inserted:

In the console I find this:

````
contentblocks-dev.js:8052 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.initializeLinkField (contentblocks-dev.js:8052)
    at Object.input.init (contentblocksbutton.js?cbv=1.6.3-pl:7)
    at Object.addField (contentblocks-dev.js:6628)
    at HTMLAnchorElement.<anonymous> (contentblocks-dev.js:7037)
    at HTMLAnchorElement.dispatch (contentblocks-dev.js:3)
    at HTMLAnchorElement.q.handle (contentblocks-dev.js:3)
initializeLinkField @ contentblocks-dev.js:8052
input.init @ contentblocksbutton.js?cbv=1.6.3-pl:7
addField @ contentblocks-dev.js:6628
(anonymous) @ contentblocks-dev.js:7037
dispatch @ contentblocks-dev.js:3
q.handle @ contentblocks-dev.js:3
````

I'll do some more reasearch If I find the time.

CU

**Comment by JayCarney** [comment]
Sorry, this was an abandoned repo, made it when I was still learning my way around ContentBlocks.

The best way to add a "button" field type to ContentBlocks (and that I use on all my projects now) is:

- Create a new link field type
- Add a setting of type text
  - Change it to display as a regular field
- Job done 😃 

Sorry for the confusion on this extra, I'll remove it from the extras repo as well to prevent any future problems

**Comment by pepebe** [comment]
Hi, thanks for your reply.

Your version has the advantage of a variable Button text.

"Link" doesn't have that option. :(

Adding a setting to do that not really a good solution.

I'm going to fix the problem soon"ish" and do a PR.

Have a nice weekend!

Cheers,

Patrick

-------------------------------------------------------------------------------------------------------

Patrick Percy Blank

Talstraße 8
74847 Obrigheim Ortsteil Mörtelstein (GoogleMaps
<https://www.google.de/maps/dir//Talstra%C3%9Fe+8,+74847+Obrigheim/@49.3575699,9.0387185,16z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x4797f34277073d99:0xfb02571977c6726b!2m2!1d9.04301!2d49.35757>
 )

Mobil: +49 (0) 152 22 52 33 49
Festnetz: +49 (0) 6262 9260 - 707

Skype: pepebedesign (immer unsichtbar, aber i.d.R erreichbar)

Email: info@pepebe.de
Web: https://pepebe.de

2017-03-17 14:58 GMT+01:00 JayCarney <notifications@github.com>:
